### ISSUE TITLE
oauth not work

### ISSUE THREAD

**Issue by ojifahru** [drajathasan/slims_oauth#1]
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution

**Comment by drajathasan** [comment]
I think is not my plugin error, that message is SQL error which means your SLiMS failed to connect. Make sure your connection access is correct like, host of your database.

**Comment by ojifahru** [comment]
Ini error di slims 9.5.2
 error nya di file slims_oauth/vendor/zein/database/src/Database/Dages/SLiMSModelContract.php baris 61 - 63
` self::$Connection = new Connector([
                'dsn' => self::init(['host' => DB_HOST, 'port' => DB_PORT, 'dbname' => DB_NAME]),
                'username' => DB_USERNAME,
                'password' => DB_PASSWORD,
                'options' => [[PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION]]
            ]);`

karena tidak ter define di config/database.php

**Comment by ojifahru** [comment]
untuk ngatasin nya saya tambahkan 
`define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'mydb');
define('DB_USERNAME', 'myusername');
define('DB_PASSWORD', 'mypassword');`

di file config/database.php

**Comment by drajathasan** [comment]
jangan pakai SLiMS 9.5.2 dulu

**Comment by ojifahru** [comment]
masih di server trial sih, belum di online kan. karena adv-search 951 error kayaknya. hasil pencarian gak pernah sesuai. padahal udah di index

**Comment by drajathasan** [comment]
Ok karena pembicaraan sudah diluar judul saya tutup. Terimakasih
